"""Excel copies of the customer statement, reorder proposal, and management review.

Figures come from the same payloads the screens already show.
"""

from vay.export_excel import write_workbook

from server.customers import stated_money


def _blank(value):
    return "" if value in ("", None) else value


def _yes(flag):
    return "Yes" if flag else "No"


def statement_reports(detail):
    """Sheets that match the customer statement: identity, aging, invoices, promises."""
    detail = detail or {}
    company = (detail.get("company_name") or "").strip()
    code = (detail.get("currency_code") or "").strip()
    symbol = (detail.get("currency_symbol") or "").strip()
    currency = symbol or code
    due_label = "Advance" if detail.get("credit") else "Amount due"
    due_value = abs(detail.get("due") or 0) if detail.get("credit") else detail.get("due")
    summary = {
        "id": "customer_statement",
        "headers": ["Metric", "Detail"],
        "rows": [
            ["Company", company],
            ["Customer", detail.get("name") or ""],
            ["Group", detail.get("group") or ""],
            ["Currency", currency],
            ["Currency code", code],
            ["Report date", detail.get("as_of_label") or detail.get("as_of") or ""],
            [due_label, stated_money(detail, due_value)],
            ["Open invoices", str(detail.get("invoices_waiting") or 0)],
            ["Note", "For your records. Generated by Vay."],
        ],
    }
    buckets = detail.get("owe_buckets") or {}
    aging = {
        "id": "statement_aging",
        "headers": ["Band", "Amount"],
        "text_headers": ["Band"],
        "rows": [
            ["0-15", buckets.get("d0_15") or 0],
            ["15-30", buckets.get("d15_30") or 0],
            ["30-45", buckets.get("d30_45") or 0],
            ["45-60", buckets.get("d45_60") or 0],
            ["60-90", buckets.get("d60_90") or 0],
            ["90+", buckets.get("d90") or 0],
        ],
    }
    invoices = {
        "id": "statement_invoices",
        "headers": ["Date", "Invoice", "What", "Still due", "Age"],
        "text_headers": ["Date", "Invoice", "What"],
        "rows": [[
            row.get("date_label") or "",
            row.get("invoice") or "",
            row.get("what") or "",
            row.get("due") or 0,
            row.get("age_days") if row.get("age_days") is not None else "",
        ] for row in (detail.get("open_invoices") or [])],
    }
    reminder = detail.get("collection_reminder") or {}
    promises = {
        "id": "statement_promises",
        "headers": ["Promised", "Date", "Remaining", "Status"],
        "text_headers": ["Date", "Status"],
        "rows": [[
            row.get("amount") or 0,
            row.get("promised_on") or "",
            row.get("remaining") if row.get("remaining") is not None else "",
            row.get("message") or (row.get("payment_status") or "").replace("_", " "),
        ] for row in (reminder.get("promises") or [])],
    }
    if reminder.get("next_step"):
        promises["rows"].append(["", "", "", "Next step: " + reminder.get("next_step")])
    return [summary, aging, invoices, promises]


def reorder_reports(built, policy=None):
    """The reorder screen, including lines left out of the purchase and held items."""
    policy = policy or {}
    built = built or {}
    identity = {
        "id": "reorder_proposal",
        "headers": ["Metric", "Detail"],
        "rows": [
            ["Company", (policy.get("company_name") or "").strip()],
            ["Currency", (policy.get("currency_symbol") or policy.get("currency_code") or "").strip()],
            ["Report date", built.get("report_date") or ""],
            ["Stock date", built.get("stock_date") or ""],
            ["Order rule", built.get("order_rule") or ""],
            ["Demand", built.get("demand_label") or ""],
            ["Budget", "" if built.get("budget") in ("", None) else built.get("budget")],
            ["Spent", "" if built.get("spent") in ("", None) else built.get("spent")],
            ["Status", built.get("status") or ""],
            ["Note", "This is a purchase proposal. It is not a purchase order."],
        ],
    }
    if built.get("status") == "unavailable":
        identity["rows"].append(["Reason", built.get("reason") or "Unavailable"])
    lines = []
    for row in list(built.get("order") or []) + list(built.get("held") or []):
        explanation = row.get("explanation") or {}
        if row.get("reserved") is None:
            supply = "Reservations and incoming orders are not in this file"
        else:
            supply = row.get("supply_label") or ""
        note = row.get("defer_reason") or row.get("review_reason") or row.get("pack_reason") or ""
        formula = explanation.get("formula") or ""
        lines.append([
            row.get("name") or "",
            _blank(row.get("pace")),
            _blank(row.get("on_hand")),
            _blank(row.get("reserved")),
            _blank(row.get("incoming_on_time")),
            _blank(row.get("incoming_late")),
            _blank(row.get("position")),
            _blank(row.get("fill_to")),
            row.get("buy_by") or "",
            _blank(row.get("lead_days")),
            row.get("reason") or "",
            _blank(row.get("suggested_qty")),
            _blank(row.get("qty")),
            _blank(row.get("pack_size")),
            _blank(row.get("minimum")),
            row.get("supplier") or "",
            _blank(row.get("unit_cost")),
            row.get("cost_label") or "",
            _yes(row.get("included")),
            _yes(row.get("manual")),
            supply,
            note,
            formula,
        ])
    grid = {
        "id": "reorder_lines",
        "headers": [
            "Item", "Pace", "On hand", "Reserved", "Incoming on time", "Incoming late",
            "Position", "Target", "Buy by", "Lead days", "Reason", "Suggested", "Qty",
            "Pack", "Minimum", "Supplier", "Unit cost", "Cost label", "Included",
            "Manual", "Supply", "Note", "Formula",
        ],
        "text_headers": [
            "Item", "Buy by", "Reason", "Supplier", "Cost label", "Included",
            "Manual", "Supply", "Note", "Formula",
        ],
        "rows": lines,
    }
    return [identity, grid]


def review_reports(payload, policy=None):
    """Weekly review totals, owners, observed sales after contact, and task rows."""
    policy = policy or {}
    payload = payload or {}
    results = payload.get("results") or {}
    promises = results.get("promises") or {}
    attribution = results.get("attribution") or (
        "Allocated receipts are counted on one task. "
        "Received since assigned is observed, not proof that the task caused the payment."
    )
    summary = {
        "id": "management_summary",
        "headers": ["Metric", "Detail"],
        "rows": [
            ["Company", (policy.get("company_name") or "").strip()],
            ["Currency", (policy.get("currency_symbol") or policy.get("currency_code") or "").strip()],
            ["Report date", payload.get("report_date") or results.get("report_date") or ""],
            ["As of", results.get("as_of") or ""],
            ["Basis", results.get("basis") or "live"],
            ["Open", str(results.get("open_count") or 0)],
            ["Overdue", str(results.get("overdue_count") or 0)],
            ["Contacts", str(results.get("contacts") or 0)],
            ["Promises kept", str(promises.get("kept") or 0)],
            ["Promises partial", str(promises.get("partial") or 0)],
            ["Promises missed", str(promises.get("missed") or 0)],
            ["Promises pending refresh", str(promises.get("pending_refresh") or 0)],
            ["Attribution", attribution],
            ["Recovery note", "A later sale is observed after a contact. It does not show that the contact caused the sale."],
        ],
    }
    owners = {
        "id": "review_by_owner",
        "headers": ["Owner", "Open", "Overdue", "Allocated"],
        "text_headers": ["Owner"],
        "rows": [[
            row.get("owner") or "",
            row.get("open") or 0,
            row.get("overdue") or 0,
            row.get("allocated") or 0,
        ] for row in (results.get("by_owner") or [])],
    }
    recovery = {
        "id": "review_recovery",
        "headers": ["Customer", "Contacted on", "Sale date", "Amount", "Note"],
        "text_headers": ["Customer", "Contacted on", "Sale date", "Note"],
        "rows": [[
            row.get("customer") or "",
            row.get("contacted_on") or "",
            row.get("sale_date") or "",
            _blank(row.get("amount")),
            "Observed after contact. Not a cause.",
        ] for row in (results.get("recovery") or [])],
    }
    tasks = {
        "id": "review_tasks",
        "headers": ["Subject", "Owner", "Status", "Due date", "Label", "Allocated", "Observed"],
        "text_headers": ["Subject", "Owner", "Status", "Due date", "Label"],
        "rows": [[
            row.get("subject_name") or "",
            row.get("owner") or "",
            row.get("status") or "",
            row.get("due_date") or "",
            row.get("label") or "",
            _blank(row.get("verified_amount")),
            _blank(row.get("observed_amount")),
        ] for row in (results.get("rows") or [])],
    }
    return [summary, owners, recovery, tasks]


def workbook_bytes(reports):
    return write_workbook(reports)
